name: Build Ubports Images

on: 
  push:
    branches:
      - Halium-11
  release:
    types: [published]

jobs:

  focal_build_miami:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Focal Build Miami
      run: |
        set -x
        sudo apt-get update
        sudo apt install build-essential ccache img2simg -y
        sudo wget https://raw.githubusercontent.com/LineageOS/android_system_tools_mkbootimg/lineage-19.1/mkbootimg.py -O /usr/bin/mkbootimg
        sudo chmod 755 /usr/bin/mkbootimg
        ./build.sh
        ./build/prepare-fake-ota.sh out/device_miami.tar.xz ota
        ./build/system-image-from-ota.sh ota/ubuntu_command out
        echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      shell: bash
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "latest"
        files: |
          out/rootfs.img
          out/boot.img
