name: Build Ubports Images

on: 
  push:
    branches:
      - Halium-11
  release:
    types: [published]

jobs:

  focal_build_miami:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Focal Build Miami
      run: |
        set -x
        sudo apt-get update
        sudo apt install build-essential ccache img2simg -y
        sudo wget https://raw.githubusercontent.com/LineageOS/android_system_tools_mkbootimg/lineage-19.1/mkbootimg.py -O /usr/bin/mkbootimg
        sudo chmod 755 /usr/bin/mkbootimg
        wget https://github.com/Halium/initramfs-tools-halium/releases/download/dynparts/initrd.img-touch-arm64 -O /home/runner/work/Huawei-kirin710/initramfs.cpio.gz
        ./build.sh
        #./build/prepare-fake-ota.sh out/device_kirin710.tar.xz ota
        #./build/system-image-from-ota.sh ota/ubuntu_command out
        #tar -czf out/rootfs.tar.gz out/rootfs.img
        echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      shell: bash
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          out/device_kirin710.tar.xz
          out/boot.img
        name: Kirin710-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
